# Generated by Django 5.2.9 on 2026-02-02 23:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('total_bets', models.IntegerField(default=0)),
                ('placed_bets', models.IntegerField(default=0)),
                ('failed_bets', models.IntegerField(default=0)),
                ('bets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ForebetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forebet_match_id', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('home_correct_score', models.IntegerField(blank=True, null=True)),
                ('away_correct_score', models.IntegerField(blank=True, null=True)),
                ('home_ht_score', models.IntegerField(blank=True, null=True)),
                ('away_ht_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'forebet_match_id'],
                'indexes': [models.Index(fields=['date', 'forebet_match_id'], name='betting_eng_date_263db8_idx')],
                'unique_together': {('forebet_match_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('home_team', models.CharField(db_index=True, max_length=200)),
                ('away_team', models.CharField(db_index=True, max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('league_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('forebet_match_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('game_url', models.URLField(blank=True, max_length=500, null=True)),
                ('game_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'home_team'],
                'indexes': [models.Index(fields=['date', 'home_team', 'away_team'], name='betting_eng_date_a514d9_idx'), models.Index(fields=['date', 'country', 'league_name'], name='betting_eng_date_064256_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('forebet_match_id__isnull', True)), fields=('date', 'home_team', 'away_team'), name='unique_match_date_teams')],
            },
        ),
        migrations.CreateModel(
            name='MarketSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('home_over_bet', models.BooleanField(default=False)),
                ('away_over_bet', models.BooleanField(default=False)),
                ('home_draw_bet', models.BooleanField(default=False)),
                ('away_draw_bet', models.BooleanField(default=False)),
                ('over_1_5_bet', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_selections', to='betting_engine.match')),
            ],
            options={
                'ordering': ['-date', 'match'],
                'indexes': [models.Index(fields=['date'], name='betting_eng_date_72ea79_idx'), models.Index(fields=['home_over_bet', 'away_over_bet', 'home_draw_bet', 'away_draw_bet', 'over_1_5_bet'], name='betting_eng_home_ov_3b1961_idx')],
                'unique_together': {('match', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ForebetTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forebet_match_id', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('league_name', models.CharField(blank=True, max_length=200, null=True)),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('game_link', models.URLField(blank=True, max_length=500, null=True)),
                ('preview_link', models.URLField(blank=True, max_length=500, null=True)),
                ('preview_html', models.TextField(blank=True, null=True)),
                ('prob_1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prob_x', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prob_2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pred', models.CharField(blank=True, max_length=10, null=True)),
                ('home_pred_score', models.IntegerField(blank=True, null=True)),
                ('away_pred_score', models.IntegerField(blank=True, null=True)),
                ('avg_goals', models.FloatField(blank=True, null=True)),
                ('kelly', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forebet_tips', to='betting_engine.match')),
            ],
            options={
                'ordering': ['-date', 'forebet_match_id'],
                'indexes': [models.Index(fields=['date', 'forebet_match_id'], name='betting_eng_date_2d3018_idx')],
                'unique_together': {('forebet_match_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CombinedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_matches', to='betting_engine.match')),
            ],
            options={
                'ordering': ['-date', 'match'],
                'indexes': [models.Index(fields=['date'], name='betting_eng_date_3a7d98_idx')],
                'unique_together': {('match', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BetwayOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('odds_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betway_odds', to='betting_engine.match')),
            ],
            options={
                'ordering': ['-date', 'match'],
                'indexes': [models.Index(fields=['date'], name='betting_eng_date_41f37d_idx')],
                'unique_together': {('match', 'date')},
            },
        ),
    ]
