# Generated by Django 5.2.9 on 2026-02-04 11:50

from django.db import migrations, models


def clear_duplicate_legacy_rows(apps, schema_editor):
    """Remove old rows with empty home_team/away_team so unique constraint can be applied."""
    db_alias = schema_editor.connection.alias
    BetwayOdds = apps.get_model('betting_engine', 'BetwayOdds')
    CombinedMatch = apps.get_model('betting_engine', 'CombinedMatch')
    MarketSelection = apps.get_model('betting_engine', 'MarketSelection')
    BetwayOdds.objects.using(db_alias).filter(home_team='', away_team='').delete()
    CombinedMatch.objects.using(db_alias).filter(home_team='', away_team='').delete()
    MarketSelection.objects.using(db_alias).filter(home_team='', away_team='').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forebettip',
            name='match',
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='BTTS_no',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='BTTS_yes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='away_draw_no_bet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='away_draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='away_team',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='away_team_over_0_5',
            field=models.FloatField(blank=True, db_column='away_team_over_0.5', null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='away_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='game_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='home_away_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='home_draw_no_bet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='home_draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='home_team',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='home_team_over_0_5',
            field=models.FloatField(blank=True, db_column='home_team_over_0.5', null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='home_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='total_over_1_5',
            field=models.FloatField(blank=True, db_column='total_over_1.5', null=True),
        ),
        migrations.AddField(
            model_name='betwayodds',
            name='total_under_3_5',
            field=models.FloatField(blank=True, db_column='total_under_3.5', null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='BTTS_no',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='BTTS_yes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='away_draw_no_bet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='away_draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='away_team',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='away_team_over_0_5',
            field=models.FloatField(blank=True, db_column='away_team_over_0.5', null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='away_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_avg_goals',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_away_pred_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_game_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_home_pred_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_kelly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_league_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_match_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_pred',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_preview_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_prob_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_prob_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='forebet_prob_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='game_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='home_away_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='home_draw_no_bet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='home_draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='home_team',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='home_team_over_0_5',
            field=models.FloatField(blank=True, db_column='home_team_over_0.5', null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='home_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='total_over_1_5',
            field=models.FloatField(blank=True, db_column='total_over_1.5', null=True),
        ),
        migrations.AddField(
            model_name='combinedmatch',
            name='total_under_3_5',
            field=models.FloatField(blank=True, db_column='total_under_3.5', null=True),
        ),
        migrations.AddField(
            model_name='forebettip',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='away_draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='away_team',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='away_team_over_0_5',
            field=models.FloatField(blank=True, db_column='away_team_over_0.5', null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='away_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='forebet_avg_goals',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='forebet_away_pred_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='forebet_home_pred_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='forebet_match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='forebet_prob_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='forebet_prob_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='forebet_prob_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='game_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='home_away_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='home_draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='home_team',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='home_team_over_0_5',
            field=models.FloatField(blank=True, db_column='home_team_over_0.5', null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='home_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='total_over_1_5',
            field=models.FloatField(blank=True, db_column='total_over_1.5', null=True),
        ),
        migrations.AlterField(
            model_name='forebettip',
            name='away_team',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='forebettip',
            name='home_team',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RunPython(clear_duplicate_legacy_rows, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='betwayodds',
            options={'ordering': ['-date', 'home_team']},
        ),
        migrations.AlterModelOptions(
            name='combinedmatch',
            options={'ordering': ['-date', 'home_team']},
        ),
        migrations.AlterModelOptions(
            name='marketselection',
            options={'ordering': ['-date', 'home_team']},
        ),
        migrations.AlterUniqueTogether(
            name='betwayodds',
            unique_together={('date', 'home_team', 'away_team')},
        ),
        migrations.AlterUniqueTogether(
            name='combinedmatch',
            unique_together={('date', 'home_team', 'away_team')},
        ),
        migrations.AlterUniqueTogether(
            name='marketselection',
            unique_together={('date', 'home_team', 'away_team')},
        ),
        migrations.AddIndex(
            model_name='betwayodds',
            index=models.Index(fields=['date', 'home_team', 'away_team'], name='betting_eng_date_6f7f11_idx'),
        ),
        migrations.AddIndex(
            model_name='combinedmatch',
            index=models.Index(fields=['date', 'home_team', 'away_team'], name='betting_eng_date_1cc37b_idx'),
        ),
        migrations.AddIndex(
            model_name='forebettip',
            index=models.Index(fields=['date', 'home_team', 'away_team'], name='betting_eng_date_d33f50_idx'),
        ),
        migrations.RemoveField(
            model_name='betwayodds',
            name='match',
        ),
        migrations.RemoveField(
            model_name='betwayodds',
            name='odds_data',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='match',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='match',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
