# Generated by Django 5.2.9 on 2026-02-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0003_refactor_betwayodds_to_json_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='betting_eng_date_5efe9e_idx')],
            },
        ),
    ]
