# Generated by Django 5.2.9 on 2026-02-05 11:11

from django.db import migrations, models
from collections import defaultdict


def migrate_forebet_tips_to_json(apps, schema_editor):
    """Migrate existing ForebetTip rows to new JSON structure (update in place to avoid NOT NULL)."""
    ForebetTip = apps.get_model('betting_engine', 'ForebetTip')
    db_alias = schema_editor.connection.alias

    # Group existing rows by date (keep row refs for in-place update)
    by_date = defaultdict(list)
    for row in ForebetTip.objects.using(db_alias).order_by('date', 'id'):
        tip_data = {
            'match_id': getattr(row, 'forebet_match_id', None),
            'time': getattr(row, 'time', None),
            'country': getattr(row, 'country', None),
            'league_name': getattr(row, 'league_name', None),
            'home_team': getattr(row, 'home_team', ''),
            'away_team': getattr(row, 'away_team', ''),
            'game_link': getattr(row, 'game_link', None),
            'preview_link': getattr(row, 'preview_link', None),
            'preview_html': getattr(row, 'preview_html', None),
            'prob_1': getattr(row, 'prob_1', None),
            'prob_x': getattr(row, 'prob_x', None),
            'prob_2': getattr(row, 'prob_2', None),
            'pred': getattr(row, 'pred', None),
            'home_pred_score': getattr(row, 'home_pred_score', None),
            'away_pred_score': getattr(row, 'away_pred_score', None),
            'avg_goals': getattr(row, 'avg_goals', None),
            'kelly': getattr(row, 'kelly', None),
        }
        by_date[row.date].append((row, tip_data))

    for date, row_tips in by_date.items():
        tips_list = [t for _, t in row_tips]
        first_row = row_tips[0][0]
        first_row.tips = tips_list
        first_row.save(using=db_alias)
        # Delete duplicate rows for this date (keep first)
        first_id = first_row.id
        ForebetTip.objects.using(db_alias).filter(date=date).exclude(pk=first_id).delete()


def migrate_forebet_results_to_json(apps, schema_editor):
    """Migrate existing ForebetResult rows to new JSON structure (update in place)."""
    ForebetResult = apps.get_model('betting_engine', 'ForebetResult')
    db_alias = schema_editor.connection.alias

    by_date = defaultdict(list)
    for row in ForebetResult.objects.using(db_alias).order_by('date', 'id'):
        result_data = {
            'match_id': getattr(row, 'forebet_match_id', None),
            'home_correct_score': getattr(row, 'home_correct_score', None),
            'away_correct_score': getattr(row, 'away_correct_score', None),
            'home_ht_score': getattr(row, 'home_ht_score', None),
            'away_ht_score': getattr(row, 'away_ht_score', None),
        }
        by_date[row.date].append((row, result_data))

    for date, row_results in by_date.items():
        results_list = [r for _, r in row_results]
        first_row = row_results[0][0]
        first_row.results = results_list
        first_row.save(using=db_alias)
        first_id = first_row.id
        ForebetResult.objects.using(db_alias).filter(date=date).exclude(pk=first_id).delete()


def migrate_combined_matches_to_json(apps, schema_editor):
    """Migrate existing CombinedMatch rows to new JSON structure (update in place)."""
    CombinedMatch = apps.get_model('betting_engine', 'CombinedMatch')
    db_alias = schema_editor.connection.alias

    by_date = defaultdict(list)
    for row in CombinedMatch.objects.using(db_alias).order_by('date', 'id'):
        if hasattr(row, 'payload') and getattr(row, 'payload', None):
            match_data = getattr(row, 'payload', {}).copy()
        else:
            match_data = {
                'time': getattr(row, 'time', None),
                'home_team': getattr(row, 'home_team', ''),
                'away_team': getattr(row, 'away_team', ''),
                'game_url': getattr(row, 'game_url', None),
                'match_confidence': getattr(row, 'match_confidence', None),
                'home_win': getattr(row, 'home_win', None),
                'draw': getattr(row, 'draw', None),
                'away_win': getattr(row, 'away_win', None),
                'home_draw_no_bet': getattr(row, 'home_draw_no_bet', None),
                'away_draw_no_bet': getattr(row, 'away_draw_no_bet', None),
                'home_draw_odds': getattr(row, 'home_draw_odds', None),
                'away_draw_odds': getattr(row, 'away_draw_odds', None),
                'home_away_odds': getattr(row, 'home_away_odds', None),
                'total_over_1.5': getattr(row, 'total_over_1_5', None),
                'total_under_3.5': getattr(row, 'total_under_3_5', None),
                'BTTS_yes': getattr(row, 'BTTS_yes', None),
                'BTTS_no': getattr(row, 'BTTS_no', None),
                'home_team_over_0.5': getattr(row, 'home_team_over_0_5', None),
                'away_team_over_0.5': getattr(row, 'away_team_over_0_5', None),
                'forebet_match_id': getattr(row, 'forebet_match_id', None),
                'forebet_country': getattr(row, 'forebet_country', None),
                'forebet_league_name': getattr(row, 'forebet_league_name', None),
                'forebet_game_link': getattr(row, 'forebet_game_link', None),
                'forebet_preview_link': getattr(row, 'forebet_preview_link', None),
                'forebet_prob_1': getattr(row, 'forebet_prob_1', None),
                'forebet_prob_x': getattr(row, 'forebet_prob_x', None),
                'forebet_prob_2': getattr(row, 'forebet_prob_2', None),
                'forebet_pred': getattr(row, 'forebet_pred', None),
                'forebet_home_pred_score': getattr(row, 'forebet_home_pred_score', None),
                'forebet_away_pred_score': getattr(row, 'forebet_away_pred_score', None),
                'forebet_avg_goals': getattr(row, 'forebet_avg_goals', None),
                'forebet_kelly': getattr(row, 'forebet_kelly', None),
            }
        by_date[row.date].append((row, match_data))

    for date, row_matches in by_date.items():
        matches_list = [m for _, m in row_matches]
        first_row = row_matches[0][0]
        first_row.matches = matches_list
        first_row.save(using=db_alias)
        first_id = first_row.id
        CombinedMatch.objects.using(db_alias).filter(date=date).exclude(pk=first_id).delete()


def migrate_market_selections_to_json(apps, schema_editor):
    """Migrate existing MarketSelection rows to new JSON structure (update in place)."""
    MarketSelection = apps.get_model('betting_engine', 'MarketSelection')
    db_alias = schema_editor.connection.alias

    by_date = defaultdict(list)
    for row in MarketSelection.objects.using(db_alias).order_by('date', 'id'):
        selection_data = {
            'time': getattr(row, 'time', None),
            'home_team': getattr(row, 'home_team', ''),
            'away_team': getattr(row, 'away_team', ''),
            'game_url': getattr(row, 'game_url', None),
            'home_over_bet': getattr(row, 'home_over_bet', False),
            'away_over_bet': getattr(row, 'away_over_bet', False),
            'home_draw_bet': getattr(row, 'home_draw_bet', False),
            'away_draw_bet': getattr(row, 'away_draw_bet', False),
            'over_1_5_bet': getattr(row, 'over_1_5_bet', False),
            'home_draw_odds': getattr(row, 'home_draw_odds', None),
            'away_draw_odds': getattr(row, 'away_draw_odds', None),
            'home_away_odds': getattr(row, 'home_away_odds', None),
            'home_win': getattr(row, 'home_win', None),
            'draw': getattr(row, 'draw', None),
            'away_win': getattr(row, 'away_win', None),
            'total_over_1.5': getattr(row, 'total_over_1_5', None),
            'home_team_over_0.5': getattr(row, 'home_team_over_0_5', None),
            'away_team_over_0.5': getattr(row, 'away_team_over_0_5', None),
            'forebet_match_id': getattr(row, 'forebet_match_id', None),
            'forebet_home_pred_score': getattr(row, 'forebet_home_pred_score', None),
            'forebet_away_pred_score': getattr(row, 'forebet_away_pred_score', None),
            'forebet_prob_1': getattr(row, 'forebet_prob_1', None),
            'forebet_prob_x': getattr(row, 'forebet_prob_x', None),
            'forebet_prob_2': getattr(row, 'forebet_prob_2', None),
            'forebet_avg_goals': getattr(row, 'forebet_avg_goals', None),
            'match_confidence': getattr(row, 'match_confidence', None),
        }
        if hasattr(row, 'extra_data') and getattr(row, 'extra_data', None):
            extra = getattr(row, 'extra_data', {})
            if isinstance(extra, dict):
                selection_data.update(extra)
        by_date[row.date].append((row, selection_data))

    for date, row_selections in by_date.items():
        selections_list = [s for _, s in row_selections]
        first_row = row_selections[0][0]
        first_row.selections = selections_list
        first_row.save(using=db_alias)
        first_id = first_row.id
        MarketSelection.objects.using(db_alias).filter(date=date).exclude(pk=first_id).delete()


def migrate_single_bet_snapshots_to_json(apps, schema_editor):
    """Migrate existing SingleBetSnapshot rows to new JSON structure."""
    SingleBetSnapshot = apps.get_model('betting_engine', 'SingleBetSnapshot')
    db_alias = schema_editor.connection.alias
    
    for row in SingleBetSnapshot.objects.using(db_alias).all():
        snapshot_data = {
            'timestamp': getattr(row, 'timestamp', None).isoformat() if getattr(row, 'timestamp', None) else None,
            'total_bets': getattr(row, 'total_bets', 0),
            'placed_bets': getattr(row, 'placed_bets', 0),
            'failed_bets': getattr(row, 'failed_bets', 0),
            'bets': getattr(row, 'bets', []),
        }
        row.snapshot = snapshot_data
        row.save(using=db_alias)


def reverse_migration(apps, schema_editor):
    """Reverse migration - this would require the old model structure, so we just clear data."""
    # For reverse, we'd need to expand JSON back to individual rows
    # This is complex and data-lossy, so we'll just clear
    ForebetTip = apps.get_model('betting_engine', 'ForebetTip')
    ForebetResult = apps.get_model('betting_engine', 'ForebetResult')
    CombinedMatch = apps.get_model('betting_engine', 'CombinedMatch')
    MarketSelection = apps.get_model('betting_engine', 'MarketSelection')
    SingleBetSnapshot = apps.get_model('betting_engine', 'SingleBetSnapshot')
    
    db_alias = schema_editor.connection.alias
    ForebetTip.objects.using(db_alias).all().delete()
    ForebetResult.objects.using(db_alias).all().delete()
    CombinedMatch.objects.using(db_alias).all().delete()
    MarketSelection.objects.using(db_alias).all().delete()
    # SingleBetSnapshot - clear snapshot field
    for row in SingleBetSnapshot.objects.using(db_alias).all():
        row.snapshot = {}
        row.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('betting_engine', '0004_add_mergedmatch'),
    ]

    operations = [
        # Step 1: Add new JSON fields
        migrations.AddField(
            model_name='combinedmatch',
            name='matches',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='forebetresult',
            name='results',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='forebettip',
            name='tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='marketselection',
            name='selections',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='singlebetsnapshot',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        # Step 2: Migrate data to JSON
        migrations.RunPython(migrate_forebet_tips_to_json, reverse_migration),
        migrations.RunPython(migrate_forebet_results_to_json, reverse_migration),
        migrations.RunPython(migrate_combined_matches_to_json, reverse_migration),
        migrations.RunPython(migrate_market_selections_to_json, reverse_migration),
        migrations.RunPython(migrate_single_bet_snapshots_to_json, reverse_migration),
        # Step 3: Update Meta options and constraints
        migrations.AlterModelOptions(
            name='combinedmatch',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='forebetresult',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='forebettip',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='marketselection',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='combinedmatch',
            name='betting_eng_date_1cc37b_idx',
        ),
        migrations.RemoveIndex(
            model_name='forebetresult',
            name='betting_eng_date_263db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='forebettip',
            name='betting_eng_date_2d3018_idx',
        ),
        migrations.RemoveIndex(
            model_name='forebettip',
            name='betting_eng_date_d33f50_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketselection',
            name='betting_eng_home_ov_3b1961_idx',
        ),
        migrations.AlterUniqueTogether(
            name='combinedmatch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='forebetresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='forebettip',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='marketselection',
            unique_together=set(),
        ),
        # Step 4: Remove old fields from SingleBetSnapshot (after snapshot field is populated)
        migrations.RemoveField(
            model_name='singlebetsnapshot',
            name='bets',
        ),
        migrations.RemoveField(
            model_name='singlebetsnapshot',
            name='failed_bets',
        ),
        migrations.RemoveField(
            model_name='singlebetsnapshot',
            name='placed_bets',
        ),
        migrations.RemoveField(
            model_name='singlebetsnapshot',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='singlebetsnapshot',
            name='total_bets',
        ),
        migrations.AlterField(
            model_name='combinedmatch',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='forebetresult',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='forebettip',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='marketselection',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='forebetresult',
            index=models.Index(fields=['date'], name='betting_eng_date_18e521_idx'),
        ),
        migrations.AddIndex(
            model_name='forebettip',
            index=models.Index(fields=['date'], name='betting_eng_date_08a3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='singlebetsnapshot',
            index=models.Index(fields=['date'], name='betting_eng_date_e3a49f_idx'),
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='BTTS_no',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='BTTS_yes',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='away_draw_no_bet',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='away_draw_odds',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='away_team_over_0_5',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='away_win',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_avg_goals',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_away_pred_score',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_country',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_game_link',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_home_pred_score',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_kelly',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_league_name',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_match_id',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_pred',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_preview_link',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_prob_1',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_prob_2',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='forebet_prob_x',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='game_url',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='home_away_odds',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='home_draw_no_bet',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='home_draw_odds',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='home_team_over_0_5',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='home_win',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='match_confidence',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='time',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='total_over_1_5',
        ),
        migrations.RemoveField(
            model_name='combinedmatch',
            name='total_under_3_5',
        ),
        migrations.RemoveField(
            model_name='forebetresult',
            name='away_correct_score',
        ),
        migrations.RemoveField(
            model_name='forebetresult',
            name='away_ht_score',
        ),
        migrations.RemoveField(
            model_name='forebetresult',
            name='forebet_match_id',
        ),
        migrations.RemoveField(
            model_name='forebetresult',
            name='home_correct_score',
        ),
        migrations.RemoveField(
            model_name='forebetresult',
            name='home_ht_score',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='avg_goals',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='away_pred_score',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='forebet_match_id',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='game_link',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='home_pred_score',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='kelly',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='league_name',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='pred',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='preview_html',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='preview_link',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='prob_1',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='prob_2',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='prob_x',
        ),
        migrations.RemoveField(
            model_name='forebettip',
            name='time',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='away_draw_bet',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='away_draw_odds',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='away_over_bet',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='away_team_over_0_5',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='away_win',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='forebet_avg_goals',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='forebet_away_pred_score',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='forebet_home_pred_score',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='forebet_match_id',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='forebet_prob_1',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='forebet_prob_2',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='forebet_prob_x',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='game_url',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='home_away_odds',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='home_draw_bet',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='home_draw_odds',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='home_over_bet',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='home_team_over_0_5',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='home_win',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='match_confidence',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='over_1_5_bet',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='time',
        ),
        migrations.RemoveField(
            model_name='marketselection',
            name='total_over_1_5',
        ),
    ]
